# Generated by Django 5.1.5 on 2025-02-03 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="fileupload",
            name="file_name",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="fileupload",
            name="file_size",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="fileupload",
            name="file_type",
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
