services:
# commented to run AWS BACKEND and FRONTEND on VERCEL, uncomment otherwise
  # frontend:
  #   build:
  #     context: ./frontend
  #     dockerfile: Dockerfile
  #   ports:
  #     - "5173:5173"  # Map localhost:5173 to React app port 5173
  #   volumes:
  #     - ./frontend:/app
  #     - /app/node_modules
  #   environment:
  #     - CHOKIDAR_USEPOLLING=true
  #   stdin_open: true
  #   tty: true
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"  # Map localhost:8000 to Django server port
    volumes:
      - ./backend:/backend
    environment:
      - DEBUG=True # Set to False in Production
    stdin_open: true
    tty: true

networks:
  backend:
    driver: bridge